homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  
  # Load Packages
  packages: !include_dir_named components/packages
hacs:
  token: 1d53d968a0f2718c06c6190d581bf5b0325466c4
  sidepanel_title: hacs
  sidepanel_icon: "mdi:github-face"
  theme: True
  
# Frontend Basic Automations
#automation: !include automations.yaml
