---
# This handles the loading of my automations
#
# https://www.home-assistant.io/docs/automation/
#
automation old: !include_dir_list ../../automations

# include automations from the gui
automation: !include ../../automations.yaml